# Generated by Django 4.0.4 on 2022-07-12 10:33

from django.db import migrations, models
import task.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_item_description_remove_item_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=191)),
                ('price', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=task.models.filepath)),
            ],
        ),
    ]
